<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>wwwroot\logo_SIC.ico</ApplicationIcon>
	  <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>

	  <InvariantGlobalization>false</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="NewFolder1\**" />
    <Content Remove="NewFolder1\**" />
    <EmbeddedResource Remove="NewFolder1\**" />
    <None Remove="NewFolder1\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CurrieTechnologies.Razor.SweetAlert2" Version="5.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.15" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.15" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.27" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.14.0" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SIC.Shared\SIC.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resources\SharedResource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>SharedResource.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\SharedResource.resx">
	    <Generator>PublicResXFileCodeGenerator</Generator>
	    <LastGenOutput>SharedResource.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="wwwroot\documentation\" />
	</ItemGroup>


</Project>
