//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIC.Frontend.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SIC.Frontend.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What would you like to add to the album?.
        /// </summary>
        public static string AlbumTitle {
            get {
                return ResourceManager.GetString("AlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audios.
        /// </summary>
        public static string Audios {
            get {
                return ResourceManager.GetString("Audios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record audio.
        /// </summary>
        public static string RecordAudio {
            get {
                return ResourceManager.GetString("RecordAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording.
        /// </summary>
        public static string Recording {
            get {
                return ResourceManager.GetString("Recording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Reels.
        /// </summary>
        public static string RecordReels {
            get {
                return ResourceManager.GetString("RecordReels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reels.
        /// </summary>
        public static string Reels {
            get {
                return ResourceManager.GetString("Reels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-record.
        /// </summary>
        public static string Rerecord {
            get {
                return ResourceManager.GetString("Rerecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Image(s).
        /// </summary>
        public static string SelectedImag {
            get {
                return ResourceManager.GetString("SelectedImag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected reel(s).
        /// </summary>
        public static string SelectedReels {
            get {
                return ResourceManager.GetString("SelectedReels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from Gallery.
        /// </summary>
        public static string SelectFromGallery {
            get {
                return ResourceManager.GetString("SelectFromGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Recording.
        /// </summary>
        public static string StopRecording {
            get {
                return ResourceManager.GetString("StopRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photos.
        /// </summary>
        public static string TakePhotos {
            get {
                return ResourceManager.GetString("TakePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Texts.
        /// </summary>
        public static string Texts {
            get {
                return ResourceManager.GetString("Texts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload audio.
        /// </summary>
        public static string UploadAudio {
            get {
                return ResourceManager.GetString("UploadAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploading.
        /// </summary>
        public static string Uploading {
            get {
                return ResourceManager.GetString("Uploading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photo.
        /// </summary>
        public static string UploadPhoto {
            get {
                return ResourceManager.GetString("UploadPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a dedication.
        /// </summary>
        public static string WriteDedication {
            get {
                return ResourceManager.GetString("WriteDedication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write your dedication here....
        /// </summary>
        public static string WriteYourDedicationHere {
            get {
                return ResourceManager.GetString("WriteYourDedicationHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
    }
}
